### ISSUE TITLE
Style Search bar, adding search function

### ISSUE THREAD

**Issue by devchristiansimon** [devchristiansimon/capstone-project#4]
## Value Proposition

**As a** user
**I need** search bar
**to be able to** search for content

## Description

![chrome_uCGF7JVTOC](https://user-images.githubusercontent.com/14675664/179958096-2854276c-9c7c-466a-b8c9-d7e9b079358b.png)

## Acceptance Criteria

- [ ] adding search bar style
- [ ] on initial render all cards are shown
- [ ] display the right content cards for search criteria
- [ ] when there is no content a message appears "no content :("

## Tasks

(for developers team)

- [ ] design a bar between header and content
- [ ] integrate an input field with an magnifying glass right to it
- [ ] integrate filter function for the keyword object
- [ ] add sr label for search bar
- [ ] at least one character required for search
- [ ] testing
