### ISSUE TITLE
Open and close card component, integrate content in card

### ISSUE THREAD

**Issue by devchristiansimon** [devchristiansimon/capstone-project#5]
## Value proposition

**As a** user
**I want to** see a new window when click on a card
**so that** i can see the additional content of the card

## Description

![chrome_rUEwWdvBdQ](https://user-images.githubusercontent.com/14675664/180416485-4b211bf4-9e2e-48a9-8776-2140a9ef3808.png)

## Acceptance criteria

- [ ] onClick on a card opens a new window
- [ ] window has a closing button
- [ ] functional video player
- [ ] display video, title, description, views and ratings

## Tasks

- [ ] Create modal component with useState
- [ ] styling the window-mock
- [ ] integrate close button in the upper right corner
- [ ] integrate player and video url from JSON
- [ ] integrate title, description views, rating from JSON
- [ ] testing

**Comment by PReichetanz** [comment]
Hi Gustl,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Acceptance Criteria
- "onClick" is something special for developers, but not for the customer ;) Let's rephrase: When clicking on a card, a new window is opened.
- When clicking the closing button of the detailed card, the detailed view is closed.
- You can start, pause, and stop the video.

## Tasks
- If you haven't done so far, you might search for the React useRef() hook in order to implement a video.

**Comment by SLS-BLN** [comment]
Just a short question: "Beschreibung" looks like a button or a form input field. Is this just my misperception or planned? Plus one typo in line 2: the word "I" is missing before "click". Best

**Comment by devchristiansimon** [comment]
> Just a short question: "Beschreibung" looks like a button or a form input field. Is this just my misperception or planned? Plus one typo in line 2: the word "I" is missing before "click". Best

The grey field visualizes the place for the the description. an input wont make sense here
