### ISSUE TITLE
include navigation bar and other sites

### ISSUE THREAD

**Issue by devchristiansimon** [devchristiansimon/capstone-project#6]
## Value proposition

**As a** user
**I want to** click on buttons
**so that** i can navigate through additional sites

## Description

![chrome_ImtCBp6wZA](https://user-images.githubusercontent.com/14675664/180419657-32225406-eec1-4f7e-a743-f527f3d3b075.png)

## Acceptance criteria

- [ ] styled navigation bar
- [ ] functional buttons in the nav bar
- [ ] able to see and click the bar from every site of the app

## Tasks

- [ ] Create navigation component
- [ ] using routes to manage the sites
- [ ] implement different header logos (SkillBro, Erstellen, Lexikon, Profil)

**Comment by PReichetanz** [comment]
Hi Gustl,

as far as I can see, there are no other pages where you can link to yet. Within an iterative workflow, it's not useful to create an navigation "because this is how it will look in two weeks". We are building an app which is completely (!) useful for the user at the very right moment, and links to more or less empty pages do not fit into this concept.

Please make sure to choose the (one) page you want to add to your app next; build this page, add a small navigation for the two pages you have right now. In further user stories, add more navigational buttons as soon as (but not before) you will need them.
